branch-defaults:
  default:
    environment: nwHacks-dev
    group_suffix: null
global:
  application_name: nwHacks
  branch: null
  default_ec2_keyname: nwHacksEC
  default_platform: Python 3.6
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
